list: $/pensoft/mailsadministration/models/groups/columns.yaml
modelClass: Pensoft\Mailsadministration\Models\Groups
title: Groups
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/mailsadministration/groups/update/:id'
